name: GitHub Actions Demo
on: 
  push:
     branches: main
     paths-ignore: .github/**
  pull_request:
          branches: main
  schedule: 
  - cron: "15 6 * * SUN" 

  workflow_dispatch:
              

jobs:
  run-build:
    name: build
    runs-on: ubuntu-latest

    steps: 
        - name: checkout
        - uses: action/checkout@v4

        - name: run script
        - run: echo "hello Eddie" >> $GITHUB_STEP_SUMMERY
         
