name: Staged_deployment

on:
  workflow_dispatch:
    inputs:
      deploy_to_production:
        description: 'Deploy to Production'
        required: true
        default: 'false'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
         run: echo Building...

  Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'workflow_dispatch'
    environment: Test
    steps:
      - name: Run tests
        run: echo Testing...

  Load-Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'workflow_dispatch'
    environment: Load-Test
    steps:
      - name: Run load tests
        run: echo Testing...
      - name: Sleep for 15 seconds
        run: sleep 15
  
Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    if: inputs.deploy_to_production == 'true'
    environment:
      name: Production
      url: https://writeabout.net
    steps:
      - name: Step 1 deploying...
        run: echo Step 1 deploying... && sleep 10
      - name: Step 2 deploying...
        run: echo Step 2 deploying... && sleep 10
      - name: Step 3 deploying...
        run: echo Step 3 deploying... && sleep 10
      - name: Step 4 deploying...
        run: echo Step 4 deploying... && sleep 10
      - name: Step 5 deploying...
        run: echo Step 5 deploying... && sleep 10
